In [1]:
#import libraries
import selenium
import requests
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

1. Write a python program which searches all the product under a particular product from www.amazon.in. 
The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search 
for guitars

In [2]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
url='https://www.amazon.in'
driver.get(url)

In [3]:
user_input=input(" Enter the product :  ")

 Enter the product :  Guiter

In [4]:
# finding web element for search job bar using id
search_product=driver.find_element_by_id("twotabsearchtextbox" )

In [5]:
search_product.send_keys(user_input)

In [6]:
search_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")

In [7]:
search_btn.click()

In [9]:
#driver.close()

2. In the above question, now scrape the following details of each product listed in first 3 pages of your 
search results and save it in a data frame and csv. In case if any product has less than 3 pages in search 
results then scrape all the products available under that product name. Details to be scraped are: "Brand 
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and 
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [ ]:
urls = []
start=0
end=3
for page in range(start,end):
    
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')    
    for i in url:
        urls.append(i.get_attribute("href")) 
        
    nxt_button=driver.find_element_by_xpath('//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    nxt_button.click()
    
Brand_name = []   
Product_name = []
Price = []
Return_Exchange = []
expected_delivery = []
Availability = [] 

for url in urls:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        brand = driver.find_element_by_xpath('//a[@id="bylineInfo"]')      
        Brand_name.append(brand.text)
    except NoSuchElementException:
        Brand.append('--')  
        
        
    try:
        name = driver.find_element_by_id('productTitle')      
        Product_name.append(name.text)
    except NoSuchElementException:
        Name.append('--')
        
        
    try:
        price = driver.find_element_by_xpath('//td[@class="a-span12"]')  
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('--')
        
    try:
        return_exchange = driver.find_element_by_xpath('//a[@class="a-size-small a-link-normal a-text-normal"]')  
        Return_Exchange.append(return_exchange.text)
    except NoSuchElementException:
        Return_Exchange.append('--')
        
        
    try:
        available= driver.find_element_by_xpath('//span[@class="a-size-medium a-color-success"]')  
        Availability.append(available.text)
    except NoSuchElementException:
        Availability.append('--')
        
        
    try:
        expected_delivery= driver.find_element_by_xpath('//span[@class="a-color-error"]')  
        Expected_delivery.append(expected_delivery.text)
    except NoSuchElementException:
        Expected_delivery.append('--')
        
        

df= pd.DataFrame({'Brand_name':Brand_name,
                  'Product_Name':Product_Name,
                  'Price':Price,
                  'Return_Exchange':Return_Exchange,
                  'Expected_delivery':Expected_delivery,
                  'Availability':Availability,
                  'urls':urls})

df

# saving in csv file
pd.DataFrame(df).to_csv('data.csv',index=0)

# 3. Write a python program to access the search bar and search button on images.google.com and scrape 10
images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [27]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://images.google.com')

In [28]:
# finding web element for search bar using id
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')

In [29]:
search_bar.send_keys('fruits')

In [30]:
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')

In [31]:
search_btn.click()

In [32]:
for _ in range(500):
    driver.execute_script("window.scrollBy(0,1000)")

In [36]:
img_urls=[]
img_tag=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

for image in img_tag:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i >= 11:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response= requests.get(img_urls[i])
    file = open(r"C:\Users\91964\Desktop\FlipRobo\images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [ ]:
driver.close()

In [41]:
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://images.google.com')
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys('Cars')
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_btn.click()

In [44]:
img_urls=[]
img_tag=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

for image in img_tag:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i >= 11:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response= requests.get(img_urls[i])
    file = open(r"C:\Users\91964\Desktop\FlipRobo\images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [45]:
driver.close()

In [47]:
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://images.google.com')
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys('machine learning')
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_btn.click()

img_urls=[]
img_tag=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

for image in img_tag:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i >= 11:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response= requests.get(img_urls[i])
    file = open(r"C:\Users\91964\Desktop\FlipRobo\images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [48]:
driver.close()

In [54]:
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://images.google.com')
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys('cakes')
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_btn.click()

img_urls=[]
img_tag=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

for image in img_tag:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i >= 11:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response= requests.get(img_urls[i])
    file = open(r"C:\Users\91964\Desktop\FlipRobo\images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [55]:
driver.close()

In [57]:
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://images.google.com')
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys('guiter')
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_btn.click()

img_urls=[]
img_tag=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

for image in img_tag:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i >= 11:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response= requests.get(img_urls[i])
    file = open(r"C:\Users\91964\Desktop\FlipRobo\images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [58]:
driver.close()

4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on
www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be 
scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, 
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the 
details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [2]:
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://www.flipkart.com')

In [3]:
# finding web element for search bar using id
search_bar=driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')

In [4]:
search_bar.send_keys('smartphone')

In [5]:
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')

In [7]:
search_btn.click()

In [9]:
Brand_name=[]
phonename=[]
color=[]
rom=[]

tag=driver.find_elements_by_xpath('//div[@class="_4rR01T"]')

for i in tag:
        Brand_name.append(i.text.split(' ')[0])
        phonename.append(i.text.split(' ')[1])
        color.append(i.text.split('(')[1].split(',')[0])
        rom.append(i.text.split('(')[1].split(',')[1])
        
len(Brand_name),len(phonename),len(color),len(rom)

(24, 24, 24, 24)

In [10]:
ram=[]
primary_camera=[]
secondary_camera=[]
display_size=[]
cam_tag=driver.find_elements_by_xpath('//div[@class="fMghEO"]')
battery=[]

for i in cam_tag:
        ram.append(i.text.split('|')[0])
        primary_camera.append(i.text.split('\n')[2].split('|')[0])
        secondary_camera.append(i.text.split('\n')[2].split('|')[1])
        display_size.append(i.text.split('\n')[1])
        battery.append(i.text.split('\n')[3])

len(ram),len(primary_camera),len(secondary_camera),len(display_size),len(battery)

(24, 24, 24, 24, 24)

In [11]:
price=[]
price_tag=driver.find_elements_by_xpath('//div[@class="_30jeq3 _1_WHN1"]')
for i in price_tag:
    
    price.append(i.text)
len(price)

24

In [12]:
url=[]
for i in driver.find_elements_by_xpath('//a[@class="_1fQZEK"]'):
    url.append(i.get_attribute("href"))
    
len(url)

24

In [13]:
dataframe=pd.DataFrame({'Brand_name':Brand_name,
            'phonename':phonename,
             'color':color,
            'rom':rom,
            'ram':ram,
            'primary_camera':primary_camera,
            'secondary_camera':secondary_camera,
            'display_size': display_size,
            'battery':battery,       
            'price':price,
            'url':url
           })   

dataframe

,Brand_name,phonename,color,rom,ram,primary_camera,secondary_camera,display_size,battery,price,url
0,realme,Narzo,Mint Green,32 GB),2 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) Display,5000 mAh Battery,"₹7,499",https://www.flipkart.com/realme-narzo-50i-mint...
1,realme,Narzo,Carbon Black,32 GB),2 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) Display,5000 mAh Battery,"₹7,499",https://www.flipkart.com/realme-narzo-50i-carb...
2,realme,Narzo,Mint Green,64 GB),4 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) Display,5000 mAh Battery,"₹8,999",https://www.flipkart.com/realme-narzo-50i-mint...
3,SAMSUNG,Galaxy,Sea Green,64 GB),4 GB RAM,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch) HD+ Display,6000 mAh Lithium-ion Battery,"₹11,499",https://www.flipkart.com/samsung-galaxy-f12-se...
4,realme,Narzo,Oxygen Green,64 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,6000 mAh Battery,"₹11,699",https://www.flipkart.com/realme-narzo-50a-oxyg...
5,realme,Narzo,Oxygen Blue,128 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,6000 mAh Battery,"₹12,499",https://www.flipkart.com/realme-narzo-50a-oxyg...
6,realme,Narzo,Carbon Black,64 GB),4 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) Display,5000 mAh Battery,"₹8,999",https://www.flipkart.com/realme-narzo-50i-carb...
7,realme,Narzo,Oxygen Blue,64 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,6000 mAh Battery,"₹11,699",https://www.flipkart.com/realme-narzo-50a-oxyg...
8,realme,C21Y,Cross Blue,32 GB),3 GB RAM,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹9,499",https://www.flipkart.com/realme-c21y-cross-blu...
9,realme,C21Y,Cross Black,64 GB),4 GB RAM,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹10,499",https://www.flipkart.com/realme-c21y-cross-bla...
10,realme,C21Y,Cross Blue,64 GB),4 GB RAM,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹10,499",https://www.flipkart.com/realme-c21y-cross-blu...
11,realme,C25Y,Metal Grey,128 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/realme-c25y-metal-gre...
12,realme,8i,Space Purple,128 GB),6 GB RAM,50MP + 2MP + 2MP,16MP Front Camera,16.76 cm (6.6 inch) Full HD+ Display,5000 mAh Battery,"₹15,999",https://www.flipkart.com/realme-8i-space-purpl...
13,realme,C21Y,Cross Black,32 GB),3 GB RAM,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹9,499",https://www.flipkart.com/realme-c21y-cross-bla...
14,SAMSUNG,Galaxy,Sky Blue,64 GB),4 GB RAM,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch) HD+ Display,6000 mAh Lithium-ion Battery,"₹11,499",https://www.flipkart.com/samsung-galaxy-f12-sk...
15,realme,C25Y,Glacier Blue,128 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/realme-c25y-glacier-b...
16,realme,C11,Cool Blue,32 GB),2 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹7,499",https://www.flipkart.com/realme-c11-2021-cool-...
17,realme,C11,Cool Grey,32 GB),2 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹7,499",https://www.flipkart.com/realme-c11-2021-cool-...
18,realme,C25_Y,Glacier Blue,64 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh LiPo Battery,"₹10,999",https://www.flipkart.com/realme-c25-y-glacier-...
19,realme,C25_Y,Metal Grey,128 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh LiPo Battery,"₹11,999",https://www.flipkart.com/realme-c25-y-metal-gr...
20,realme,C25_Y,Glacier Blue,128 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh LiPo Battery,"₹11,999",https://www.flipkart.com/realme-c25-y-glacier-...
21,realme,C25_Y,Metal Grey,64 GB),4 GB RAM,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh LiPo Battery,"₹10,999",https://www.flipkart.com/realme-c25-y-metal-gr...
22,realme,C11,Cool Blue,64 GB),4 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹8,999",https://www.flipkart.com/realme-c11-2021-cool-...
23,realme,C11,Cool Grey,64 GB),4 GB RAM,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹8,999",https://www.flipkart.com/realme-c11-2021-cool-...

In [14]:
# saving in csv file
pd.DataFrame(dataframe).to_csv('data1.csv',index=0)

# 5.Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [64]:
# import regex(regular expression)
import re

In [59]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://www.google.co.in/maps')

In [60]:
# finding web element for search job bar using id
search_city=driver.find_element_by_id("searchboxinput" )

In [61]:
search_city.send_keys('kolkata')

In [62]:
search_btn=driver.find_element_by_xpath('/html/body/div[3]/div[9]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/button')

In [63]:
search_btn.click()

In [74]:
url=driver.current_url
try:
    latti_longi=re.findall(r'@(.*)data',url)         
except:
    print('exception:', e)

latti_longi

['22.6757521,88.0495301,10z/']

In [170]:

lattitude_longitude=[]
tag=driver.find_elements_by_xpath('//button[@class="nGhxh-tv6Bve GaSlwc-uhFGfc-WsjYwc-zfKixb-UacCoe"]')
for i in tag:
    lattitude_longitude.append(i.text)
lattitude_longitude

['22.547712, 88.350281']

In [75]:
driver.close()

# 6. Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) from trak.in.

In [28]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
url=('https://trak.in/india-startup-funding-investment-2015/')
driver.get(url)
time.sleep(2)

In [31]:
# Defining Variables
slno=[]# empty list
date=[]# empty list
startupname=[]# empty list
industry=[]# empty list
subvertical=[]# empty list
city=[]# empty list
investors=[]# empty list
investment_type=[]# empty list
amount=[]# empty list

sl_tag=driver.find_elements_by_xpath('//td[@class="column-1"]')
date_tag=driver.find_elements_by_xpath('//td[@class="column-2"]')
start_tag=driver.find_elements_by_xpath('//td[@class="column-3"]')
industry_tag=driver.find_elements_by_xpath('//td[@class="column-4"]')
sub_tag=driver.find_elements_by_xpath('//td[@class="column-5"]')
city_tag=driver.find_elements_by_xpath('//td[@class="column-6"]')
investor_tag=driver.find_elements_by_xpath('//td[@class="column-7"]')
type_tag=driver.find_elements_by_xpath('//td[@class="column-8"]')
amount_tag=driver.find_elements_by_xpath('//td[@class="column-9"]')
for j in sl_tag:
     slno.append(j.text)
for j in date_tag:
     date.append(j.text)
for i in start_tag:
    startupname.append(i.text)   
for j in industry_tag:
     industry.append(j.text)
for j in sub_tag:
     subvertical.append(j.text)
for j in city_tag:
     city.append(j.text)
for j in investor_tag:
     investors.append(j.text)
for j in type_tag:
     investment_type.append(j.text)
for j in amount_tag:
     amount.append(j.text)
                
# Make data frame of funding deals:    

Funding_deals=pd.DataFrame({})
Funding_deals['Sl.no']=slno[:24]
Funding_deals['Date']=date[:24]
Funding_deals['StartupName']=startupname[:24]
Funding_deals['Industry']=industry[:24]
Funding_deals['Subvertical']=subvertical[:24]
Funding_deals['City']=city[:24]
Funding_deals['Investors']=investors[:24]
Funding_deals['Investment_Type']=investment_type[:24]
Funding_deals['Amount']=amount[:24]
Funding_deals

,Sl.no,Date,StartupName,Industry,Subvertical,City,Investors,Investment_Type,Amount
0,1,01/04/2021,BYJU’S,Edu-tech,Online tutoring,Bengaluru,Innoven Capital,Series F,"460,000,000"
1,2,05/04/2021,Meesho,E-commerce,Online reselling platform,Bengaluru,SoftBank Vision Fund 2,Series E,"300,000,000"
2,3,14/04/2021,Swiggy,Online Food Delivery,Online Food Delivery,Bengaluru,"Amansa Holdings, Carmignac, Falcon Edge Capita...",Series J,"343,000,000"
3,4,07/04/2021,Groww,FinTech,Investment platform,Bengaluru,"MC Global Edtech, B Capital, Baron, others",Series D,"83,000,000"
4,5,14/04/2021,Beldara,E-commerce,Global B2B marketplace,Mumbai,Hindustan Media Ventures,Venture,"7,400,000"
5,1,04/03/2021,DealShare,E-commerce,Online shopping platform,"Jaipur, Rajasthan",Innoven Capital,Debt Financing,"250,000,000"
6,2,31/03/2021,Uniphore,Technology,Conversational Service Automation (CSA),Palo Alto,Sorenson Capital Partners,Series D,"140,000,000"
7,3,30/03/2021,Dunzo,E-commerce,Hyper-local delivery app,Bengaluru,Krishtal Advisors Pte Ltd,Series E,"8,000,000"
8,4,30/03/2021,BYJU’S,Edu-tech,Online tutoring,Bengaluru,"MC Global Edtech, B Capital, Baron, others",Series F,"460,000,000"
9,5,23/03/2021,SkilloVilla,Edu-tech,Career and job-oriented upskilling.,Bengaluru,"Titan Capital, others",Seed,"300,000,000"
10,6,25/03/2021,CityMall,E-commerce,Social ecommerce and online grocery platform,Gurgaon,Accel Partners,Series A,"11,000,000"
11,7,26/03/2021,DotPe,FinTech,Commerce and payments platform to offline ente...,Gurgaon,PayU,Series A,"27,500,000"
12,1,11/02/2021,Doubtnut,Edu Tech,E-Learning Platform,Gurgaon,"SIG Global, Sequoia Capital, WaterBridge Ventu...",Series B,"2,500,000"
13,2,22/02/2021,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,"Tiger Global, Kora",Venture,"250,000,000"
14,3,19/02/2021,Fingerlix,Hospitality,Semi-cooked food delivery app,Mumbai,"Rhodium Trust, Accel Partners and Swiggy",Series C,"2,747,045.20"
15,4,17/02/2021,Zolve,FinTech,Global Neobank Venture,Mumbai,Accel Partners and Lightspeed Venture Partners,Seed,"1,50,00,000"
16,5,15/02/2021,KreditBee,Finance,Digital lending platform,Bengaluru,Azim Premji’s PremjiInvest and South Korea’s M...,Series C,"75,000,000"
17,6,12/02/2021,Pepperfry,E-commerce,Multi-brand furniture brand,Mumbai,InnoVen Capital,Debt Financing,"4,773,958"
18,7,12/02/2021,Grofers,E-Commerce,Online supermarket,Gurgaon,SoftBank Vision Fund (SVF),Unspecified,"55,000,000"
19,8,09/02/2021,Nothing,Technology,Consumer Technology Venture,London,GV,Series A,"15,000,000"
20,9,09/02/2021,SplashLearn,EdTech,Game-based learning programme,Gurgaon,Owl Ventures,Series C,"18,000,000"
21,7,11/01/2021,True Elements,Food Startup,Whole Food plant based Nashta,Pune,SIDBI Venture Capital,Series,"100,000,000"
22,3,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
23,1,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"

In [32]:
driver.close()

7. Write a program to scrap all the available details of best gaming laptops from digit.in

In [43]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
url='https://www.digit.in'
driver.get(url)

In [45]:
gaming=driver.find_element_by_xpath("/html/body/div[2]/div/div[4]/ul/li[4]/a")
gaming.click()

In [48]:
time.sleep(2)
laptop=driver.find_element_by_xpath('/html/body/div[4]/div/div/div[2]/div[5]/div[1]/div/button[2]')
laptop.click()

In [51]:
best_gaming=driver.find_element_by_xpath("/html/body/div[4]/div/div/div[3]/div[2]/ul/li[1]/a")
driver.get(best_gaming.get_attribute('href'))

In [106]:
product_name = []
name=driver.find_elements_by_xpath("//div[@class='right-container']/div/a/h3")
for i in name:
    product_name.append(i.text)

Price = []
price=driver.find_elements_by_xpath('//table[@id="summtable"]//tr//td[3]')
for i in price:
    Price.append(i.text)

In [111]:
OS = []
os=driver.find_elements_by_xpath('//div[@class="value"]')
for i in os:
    OS.append(i.text)
OS=OS[0::4]
len(OS)

10

In [110]:
display=[]
dis=driver.find_elements_by_xpath('//div[@class="value"]')
for i in dis:
    display.append(i.text)
display=display[1::4]
len(display)

10

In [109]:
processor=[]
pro=driver.find_elements_by_xpath('//div[@class="value"]')
for i in pro:
    processor.append(i.text)
processor=processor[2::4]
len(processor)

10

In [108]:
memory=[]
tag_=driver.find_elements_by_xpath('//div[@class="value"]')
for i in tag_:
    memory.append(i.text)
memory=memory[3::4]
len(memory)

10

In [127]:
weight=[]
tag2=driver.find_elements_by_xpath('//div[@class="Spcs-details"]/table/tbody/tr[7]/td[3]')
for i in tag2:
    weight.append(i.text)

In [125]:
dimension=[]
tag3=driver.find_elements_by_xpath('//div[@class="Spcs-details"]/table/tbody/tr[8]/td[3]')
for i in tag3:
    dimension.append(i.text)

graphics_processor=[]
tag1=driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[9]/td[3]")
for i in tag1:
    graphics_processor.append(i.text)

In [128]:
df=pd.DataFrame({"Product_Name":product_name,
                "Price":Price,
                 "OS":OS,
                 "Display":display,
                 "Processor":processor,
                 "Memory":memory,
                 "Weight":weight,
                 "Dimension":dimension,
                 "Graphics_processor":graphics_processor
                })
df

,Product_Name,Price,OS,Display,Processor,Memory,Weight,Dimension,Graphics_processor
0,ACER NITRO 5,"₹ 129,990",WINDOWS 10,"15.6"" (1920 X 1080)",AMD RYZEN 9 OCTA CORE | 2.4 GHZ,1 TB HDD/16 GBGB DDR4,2.4,363.4 x 255 x 23.9,NVIDIA GeForce RTX 3070
1,MSI STEALTH 15M,"₹ 134,990",WINDOWS 10,"15.6"" (1920 X 1080)",INTEL CORE I7 11TH GEN - 11375H | NA,1 TB SSD/16 GBGB DDR4,1.7,358.3 x 248 x 16.15,NVIDIA GeForce RTX 3060
2,ASUS ROG STRIX SCAR 15,"₹ 268,990",WINDOWS 10,"15.6"" (2560 X 1440)",AMD RYZEN 9 OCTA CORE - 5900HX | 3.3 GHZ,2 TB SSD/32 GBGB DDR4,2.30,354 x 259 x 22.6,NVIDIA GeForce RTX 3080
3,ALIENWARE AREA 51M R2,"₹ 342,989",WINDOWS 10 HOME,"17.3"" (1920 X 1080)",10TH GEN INTEL® CORE™ I7-10700 | 2.90 GHZ,1 TB SSD/16 GBGB DDR4,4.1,27.65 x 402.6 x 319.14,Intel® UHD Graphics 630
4,ALIENWARE M15 R3,"₹ 319,990",WINDOWS 10 HOME,"15.6"" (3840 X 2160)",10TH GEN INTEL® CORE™ I9-10980HK | NA,1 TB SSD/16 GBGB DDR4,NA,NA,NA
5,ASUS ROG STRIX SCAR 15,"₹ 215,990",WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 9 5900HX | 3.3 GHZ,1 TB SSD/16 GBGB DDR4,2.30,35.4 x 25.9 x 2.26,NVIDIA® GeForce RTX™ 3070
6,ASUS ZEPHYRUS G14,"₹ 164,990",WINDOWS 10 HOME,"14"" (1920 X 1080)",AMD 3RD GEN RYZEN 9 | 3.3 GHZ,1 TB SSD/16 GBGB DDR4,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060
7,LENOVO LEGION 5I,"₹ 76,988",WINDOWS 10 PRO,"15.6"" (1920 X 1080)",10TH GEN INTEL® CORE™ I5-10300H | 2.50 GHZ,1 TB SSD/16 GBGB DDR4,2.3,363.06 x 259.61 x 23.57,NVIDIA® GeForce® GTX 1650 4GB
8,ASUS ROG ZEPHYRUS DUO 15,"₹ 185,000",WINDOWS 10,"15.6"" (3840 X 1100)",INTEL CORE I7 10TH GEN 10875H | NA,512 GB SSD/4 GBGB DDR4,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q
9,ACER ASPIRE 7 GAMING LAPTOP,"₹ 57,990",WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 5-5500U HEXA-CORE | NA,512 GB SSD/8 GBGB DDR4,2.15,2.29 x 36.3 x 25.4,NVIDIA® GeForce® GTX 1650

In [129]:
driver.close()

# 8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [109]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
driver.get('https://www.forbes.com/billionaires/')

In [110]:
# Defining Variables
Rank=[]
rank_tag=driver.find_elements_by_xpath('//div[@class="rank"]')

for j in rank_tag:
     Rank.append(j.text)
len(Rank)

200

In [111]:
Name=[]
name_tag=driver.find_elements_by_xpath('//div[@class="personName"]')

for j in name_tag:
     Name.append(j.text)
len(Name)

200

In [112]:
Net_worth=[]
net_tag=driver.find_elements_by_xpath('//div[@class="netWorth"]')

for j in net_tag:
     Net_worth.append(j.text)
len(Net_worth)

200

In [117]:
Age=[]
age_tag=driver.find_elements_by_xpath('//div[@class="age"]')

for j in age_tag:
     Age.append(j.text)
len(Age)

200

In [113]:
citizen=[]
citizen_tag=driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')

for j in citizen_tag:
     citizen.append(j.text)
len(citizen)

200

In [116]:
source=[]
source_tag=driver.find_elements_by_xpath('//div[@class="source-column"]')

for j in source_tag:
     source.append(j.text)
len(source)

200

In [119]:
industry=[]
industry_tag=driver.find_elements_by_xpath('//div[@class="category"]')

for j in industry_tag:
     industry.append(j.text)
len(industry)

200

In [127]:
Billionaires=pd.DataFrame({'Rank':Rank,'Name':Name,
                           'Net_worth':Net_worth,
                           'Age':Age,
                           'Citizen':citizen,
                           'Source':source,
                           'Industry': industry
                          })
Billionaires

,Rank,Name,Net_worth,Age,Citizen,Source,Industry
0,1.,Jeff Bezos,$177 B,,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,,Colombia,banking,Finance & Investments

# 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video

In [5]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
url='https://www.youtube.com'
driver.get(url)

In [6]:
search_bar=driver.find_element_by_xpath('/html/body/ytd-app/div/div/ytd-masthead/div[3]/div[2]/ytd-searchbox/form/div[1]/div[1]/input')

In [7]:
search_bar.send_keys("Dance with Deepti")

In [8]:
search_btn=driver.find_element_by_id("search-icon-legacy")

In [9]:
search_btn.click()

In [10]:
video_link=driver.find_element_by_xpath("//yt-formatted-string[@class ='style-scope ytd-video-renderer']")

In [11]:
video_link.click()

In [46]:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [49]:
comments=[]
comments_tag=driver.find_elements_by_id("content-text")
for i in comments_tag:
    try:
        comments.append(i.text)
    except:
        comments.append('--')
len(comments)

1460

In [48]:
upvotes=[]
likes=[]
upvote = driver.find_elements_by_xpath("//span[@class='style-scope ytd-comment-action-buttons-renderer']")
for i in upvote:
    upvotes.append(i.text)
    
for i in range(1,len(upvotes),2):
    likes.append(upvotes[i]) 
len(likes)

1460

In [56]:
time=[]

time_tag=driver.find_elements_by_xpath('//yt-formatted-string[@class="published-time-text above-comment style-scope ytd-comment-renderer"]')
for i in time_tag:
    time.append(i.text)
len(time)

1460

In [57]:
df=pd.DataFrame({'Comments':comments[:500],
                 'likes':likes[:500],
                 'Time': time[:500]
                  })
df

,Comments,likes,Time
0,Thanks a looot... ❤\nI lost 5kgs 😍\nThank you ...,194,1 month ago
1,Loved these workouts. Much effective and effic...,16,2 months ago
2,I started my weight loss journey yesterday and...,64,2 months ago
3,"The workout was really awesome, first time I c...",13,1 month ago
4,My current favorite workout! The steps are so ...,22,3 months ago (edited)
...,...,...,...
495,Monday-Day 1\nDay 2 done\n.\n.,3,3 months ago (edited)
496,thanks mam it was very enjoyfull session,,4 months ago
497,Hi! Today is my first day. Only for fitness I ...,,1 month ago (edited)
498,Burnt 170 calories in this session. Thank You! 😘,11,8 months ago
499,Awesome learned exercise as well as dance than...,,2 months ago

In [59]:
driver.close()

10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in 
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, 
overall reviews, privates from price, dorms from price, facilities and property description

In [76]:
#lets first connect to webdriver
driver=webdriver.Chrome(r'C:\Users\91964\Desktop\nazia\chromedriver_win32\chromedriver.exe')
url='https://www.hostelworld.com/st/hostels/europe/england/london'
driver.get(url)

In [ ]:
btn=driver.find_element_by_xpath('/html/body/div[3]/div/div/div/header/div[2]/div[2]/div[4]/div/div/div/div[3]/div/a')

btn.click()

In [ ]:
name=[]

while(True):
    name_=driver.find_elements_by_xpath('//h2[@class="title title-6"]')
    for i in name_:
        name.append(i.text) 

    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

In [196]:
distance=[]
while(True):
    dis_=driver.find_elements_by_xpath('//span[@class="description"]')
    for i in dis_:
        distance.append(i.text)
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

22

In [193]:
overall_review=[]
while(True):
    reviewtag=driver.find_elements_by_xpath('//div[@class="keyword"]/span')
    for i in reviewtag:
        overall_review.append(i.text)
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

22

In [194]:
total_review=[]
while(True):
    review_tag=driver.find_elements_by_xpath('//div[@class="reviews"]')
    for i in review_tag:
        total_review.append(i.text)
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

22

In [224]:
privates_price=[]
while(True):
    privates_tag=driver.find_elements_by_xpath('//div[@class="price-col"]')
    for i in privates_tag:
        privates_price.append(i.text.split('\n')[-1])
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break
        
privates_price=privates_price[0: :2 ]

22

In [208]:
dorm_price=[]
while(True):
    tag=driver.find_elements_by_xpath('//div[@class="price-col"]')
    for i in tag:
        dorm_price.append(i.text.split('\n')[-1])
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break
dorm_price=dorm_price[1: :2 ]

22

In [212]:
facility=[]
while(True):
    facilitytag=driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]')
    for i in facilitytag:
        facility.append(i.text)
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

22

In [263]:
property_des=[]
url=[]
for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]'):
    url.append(i.get_attribute('href')) 
    

    try:
        pro_des = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/section/div[6]/div/div[2]/div[2]/div/div[2]')
        property_des.append(pd.text)
    except NoSuchElementException:
        property_des.append("No Description")  

(pro_des)

[]

In [252]:
ratings=[]
url=[]
for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]'):
    url.append(i.get_attribute('href'))
    
    rate_=driver.find_elements_by_xpath("//div[@class='score orange big']")
    for i in rate_:
        try:
            ratings.append(i.text)
        except NoSuchElementException:
            ratings.append("No Rating")

In [249]:
london_hostel=pd.DataFrame({'Hostel_Name':name,
                           'Distance':distance,
                           'Ratings':ratings[:22],
                           'Overall_review':overall_review,
                           'Total_review':total_review,
                           'privates_price':privates_price,
                           'dorm_price':dorm_price,
                            'Facility':facility,
                            #'Pro_des':pro_des 
                           }) 
london_hostel

,Hostel_Name,Distance,Ratings,Overall_review,Total_review,privates_price,dorm_price,Facility
0,Barry House,Bed and Breakfast - 4.2km from city centre,6.7,Fabulous,7 Total Reviews,Rs5970,No Dorms Available,Free WiFi\nFree Breakfast
1,Marble Arch Inn,Hotel - 3.5km from city centre,8.5,Superb,215 Total Reviews,Rs5615,No Dorms Available,
2,The Dover,Hotel - 1.9km from city centre,9.2,No Rating,4 Total Reviews,Rs10624,No Dorms Available,Free WiFi\nFree Breakfast
3,Best Western Boltons London Kensington,Hotel - 5.4km from city centre,7.5,Rating,2 Total Reviews,Rs9349,No Dorms Available,Free WiFi
4,Elmwood Hotel,Hotel - 3.2km from city centre,9.4,Good,113 Total Reviews,Rs5565,No Dorms Available,
5,Hyde Park Court Hotel,Hotel - 4.3km from city centre,9.0,No Rating,136 Total Reviews,Rs11636,No Dorms Available,Free WiFi\nFree Breakfast
6,Budget London Apartments,Apartment - 8.2km from city centre,7.4,Rating,356 Total Reviews,Rs5565,No Dorms Available,Free WiFi
7,Fairway Hotel,Bed and Breakfast - 3.3km from city centre,7.6,No Rating,44 Total Reviews,Rs6223,No Dorms Available,Free WiFi\nFree Breakfast
8,Golders Park Hotel,Hotel - 10.4km from city centre,8.0,No Rating,0 Total Reviews,Rs4250,No Dorms Available,Free WiFi
9,Wellesley Hotel,Hotel - 14.7km from city centre,9.3,No Rating,0 Total Reviews,Rs5009,No Dorms Available,Free WiFi
10,Paramount Hotel,Hotel - 5.7km from city centre,6.8,Fabulous,25 Total Reviews,Rs8600,No Dorms Available,
11,St George Hotel,Hotel - 3.5km from city centre,9.2,Fabulous,675 Total Reviews,Rs2530,No Dorms Available,Free Breakfast
12,Belgrave Hotel London,Hotel - 2.2km from city centre,8.3,Rating,4 Total Reviews,Rs7133,No Dorms Available,Free WiFi\nFree Breakfast
13,Aron Guest House,Bed and Breakfast - 13.1km from city centre,8.5,No Rating,26 Total Reviews,Rs6071,No Dorms Available,Free WiFi
14,Beaconsfield,Hotel - 8.6km from city centre,8.8,No Rating,28 Total Reviews,Rs5970,No Dorms Available,Free WiFi
15,Victor Hotel,Hotel - 1.8km from city centre,8.7,No Rating,2 Total Reviews,Rs9754,No Dorms Available,Free WiFi
16,Kip Hotel,Hotel - 6.8km from city centre,7.1,Superb,52 Total Reviews,Rs6071,No Dorms Available,Free WiFi
17,Green Rooms,Hotel - 10.8km from city centre,7.9,Superb,76 Total Reviews,No Privates Available,Rs2477,Free WiFi
18,23 Matheson Road,Bed and Breakfast - 6.2km from city centre,7.2,No Rating,6 Total Reviews,Rs5767,No Dorms Available,
19,Park Hotel Essex,Hotel - 24.1km from city centre,8.3,Fabulous,109 Total Reviews,Rs11636,No Dorms Available,Free Breakfast\nFollows Covid-19 sanitation gu...
20,Cranbrook Hotel,Hotel - 14.8km from city centre,7.6,No Rating,58 Total Reviews,Rs5565,No Dorms Available,Free Breakfast\nFollows Covid-19 sanitation gu...
21,TLK Apartments & Hotel,Hotel - 19.9km from city centre,8.5,No Rating,0 Total Reviews,Rs9487,No Dorms Available,Free WiFi

In [ ]:
driver.close()